# Generated by Django 3.2.15 on 2025-02-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0012_alter_orderitem_part_returned_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="hardware", name="credits", field=models.IntegerField(default=0),
        ),
    ]
