# Generated by Django 3.2.15 on 2025-11-28 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0012_auto_20250125_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='what_role_in_team_setting',
        ),
        migrations.AddField(
            model_name='application',
            name='one_million_dollars_investment',
            field=models.TextField(default='', help_text='If you had a million dollars to invest in one technology brand, what would it be and why?', max_length=1000),
        ),
        migrations.AlterField(
            model_name='application',
            name='conduct_agree',
            field=models.BooleanField(default=False, help_text='I have read and agree to the <a href="https://github.com/MLH/mlh-policies/blob/main/code-of-conduct.md" rel="noopener noreferrer" target="_blank">MLH code of conduct</a>.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='logistics_agree',
            field=models.BooleanField(default=False, help_text='I authorize you to share my application/registration information with Major League Hacking for event administration, ranking, and MLH administration in-line with the <a href="https://github.com/MLH/mlh-policies/blob/main/privacy-policy.md" rel="noopener noreferrer" target="_blank">MLH Privacy Policy</a>. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/blob/main/contest-terms.md" rel="noopener noreferrer" target="_blank">MLH Contest Terms and Conditions</a> and the <a href="https://mlh.io/privacy" rel="noopener noreferrer" target="_blank">MLH Privacy Policy.</a>'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d[\\d\\s()-]{7,}$', message='Enter a valid phone number.')]),
        ),
        migrations.AlterField(
            model_name='application',
            name='what_past_experience',
            field=models.TextField(default='', help_text='Describe the most significant challenges you faced in a project/hackathon. What did you learn from them?', max_length=1000),
        ),
    ]
