# Generated by Django 3.2.15 on 2026-07-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0014_update_mlh_checkbox_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="logistics_agree",
            field=models.BooleanField(
                default=False,
                help_text='I authorize you to share my application/registration information with Major League Hacking for event administration, ranking, and administration (including the creation of linked accounts on MLH and <a href="https://dev.to" rel="noopener noreferrer" target="_blank">DEV</a>) in line with the MLH Privacy Policy. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/blob/main/contest-terms.md" rel="noopener noreferrer" target="_blank">MLH Contest Terms and Conditions</a> and the MLH Privacy Policy.',
            ),
        ),
    ]
