# Generated by Django 3.2.15 on 2025-02-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="team", name="credits", field=models.IntegerField(default=300),
        ),
    ]
