# Generated by Django 3.2.15 on 2026-07-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_interestsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interestsubmission",
            name="conduct_agree",
            field=models.BooleanField(
                default=False,
                help_text='I have read and agree to the <a href="https://github.com/MLH/mlh-policies/blob/main/code-of-conduct.md" rel="noopener noreferrer" target="_blank">MLH Code of Conduct</a>.',
            ),
        ),
        migrations.AlterField(
            model_name="interestsubmission",
            name="email_agree",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="I authorize MLH + DEV to send me occasional emails about relevant events, career opportunities, and community announcements.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interestsubmission",
            name="logistics_agree",
            field=models.BooleanField(
                default=False,
                help_text='I authorize you to share my application/registration information with Major League Hacking for event administration, ranking, and administration (including the creation of linked accounts on MLH and <a href="https://dev.to" rel="noopener noreferrer" target="_blank">DEV (dev.to)</a>) in line with the <a href="https://github.com/MLH/mlh-policies/blob/main/privacy-policy.md" rel="noopener noreferrer" target="_blank">MLH Privacy Policy</a>. I further agree to the terms of both the <a href="https://github.com/MLH/mlh-policies/blob/main/contest-terms.md" rel="noopener noreferrer" target="_blank">MLH Contest Terms and Conditions</a> and the <a href="https://github.com/MLH/mlh-policies/blob/main/privacy-policy.md" rel="noopener noreferrer" target="_blank">MLH Privacy Policy</a>.',
            ),
        ),
    ]
